sudo: required

before_install:
    # Install phantomjs dependencies
    - sudo apt-get install nodejs
    - sudo npm install -g phantomjs-prebuilt

language: python
python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "3.6"
  - "3.6-dev" # 3.6 development branch
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script: python3 ./setup.py
